server:     #服务配置项
  port: 10010     #修改服务启动端口

spring:     #spring配置项
  application:      #应用配置项
    name: gateway-demo      #修改应用名称
  cloud:      #springcloud配置项
    gateway:      #gateway配置项
      routes:       #配置路由
        - id: service-demo-route      #路由id，根据个人习惯命名
#          uri: http://127.0.0.1:8083      #代理服务器地址，这里的服务地址写死了，在实际编码中明显是不合理的
          uri: lb://service-demo      #代理服务器地址；面向服务的路由：lb://service-demo；lb：表示LoadBalanced，基于Ribbon的负载均衡，从eureka中获取对应服务名称的地址；service-demo：必须是在eureka中已经注册了的程序服务应用名称
          predicates:     #路由断言，可以匹配请求的路径
            - Path=/user/**     #表示请求路径中带user的都会执行该路由, 配置多个断言用","隔开
#        - id: consumer-demo-route      #配置多个路由id
#          uri: http://127.0.0.1:8080
#          predicates:
#            - Path=/user/**,/userFeign/**

eureka:     #eureka配置项
  client:     #eureka客户端配置项
    service-url:      #eureka服务路径配置项
      defaultZone: http://127.0.0.1:10086/eureka      #eureka默认服务路径
  instance:     #eureka实例配置项
    prefer-ip-address: true     #更倾向使用ip地址而不是host名称
