spring:     #spring配置项
  application:      #应用配置项
    name: consumer-demo     #配置当前应用名称

eureka:     #eureka配置项
  client:     #eureka客户端配置项
    service-url:      #配置eureka服务地址
#      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka      #eureka集群环境配置eureka服务地址
      defaultZone: http://127.0.0.1:10086/eureka      #配置eureka注册服务地址
    registry-fetch-interval-seconds: 30     #客户端拉取eureka服务列表地址时间间隔，默认30秒